### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/smart-contract-backend#1]
IOHK runs Buildkite infrastructure, access via Google account:
https://buildkite.com/input-output-hk

https://buildkite.com/docs/tutorials/docker-containerized-builds

- [ ] Add Instanbul + https://coveralls.io/

**Comment by rhyslbw** [comment]
Notes from task in the former`smart-contract-docker-execution` repositpory:

> The buildkite env will require access to the Docker daemon, as well as NodeJS deps

**Comment by Sam-Jeston** [comment]
I have reached out to the devops-crossteam-ci channel to ask for direction regarding buildkite vs travis. Specifically, this is what was said:

"The requirements for our builds are simple. Docker and nodejs. I started looking at configuring buildkite and thought a plugin to run the jobs in Docker containers themselves might be appropriate and reduce the build dependency to only Docker (https://github.com/buildkite-plugins/docker-compose-buildkite-plugin). At that point I saw that the linux agents are running buildkite agent v2.x, and the windows and darwin argents are running 3.x. v2.x does not have plugin support, and it doesn’t look like the v3.x agents have been configured to support plugins (I get this error: Error: Can’t checkout plugins without a `plugins-path`), which I figure shows plugins are not used on our agents.

So what is the recommended approach here? And is buildkite the preferred CI tool? It’d be trivial to configure this build on Travis if that’s an option."

**Comment by Sam-Jeston** [comment]
We have been given our own AWS account for the Application Platform, and for now have received te direction from DevOps that we can run our CI in isolation.

The most logical CI tool to use is Buildkite, as this is what the rest of the company is using, and will allow us to more easily re-integrate to the mainstream in the future. The PR that achieves this is here: #45 

I have some pretty major concerns regarding Buildkite. These include:

1. Being forced to run the buildkite-agent natively installed on Ubuntu over the Docker agent, as the docker agent would crash unexpectedly. The local agent was an absolute pain to work with. pre-command and post-command hooks had to be used to ensure the Docker network was in the correct state and to be able to cleanup the filesystem after a build.
2. As the build becomes more complex (DB dependencies, etc) we will need to use the docker-compose plugin over the docker plugin. The issue I had with that compose plugin was as soon as a test failed, the build exited without any test failure logs, making debugging incredibly difficult.

Our other options include:

1. A well established self-hosted solution
2. AWS Codepipeline
3. A managed solution (Travis Enterprise etc)

**Self-Hosted Solutions**

Any of the big self-hosted solutions will without a doubt meet our needs. TeamCity and Jenkins come to mind. These solutions are mature, have fixed ways of managing dependencies and running builds in isolation (containers etc) and managing build secrets. The only question is if it is worth going this road to only have DevOps force us in another direction in coming weeks / months.

**AWS Codepipeline**

This is a CI tool provided by AWS. Its biggest drawback is integration with any 3rd party provider needs to be done manually. Its benefit is certainly its tight integration with AWS & the associated services. So the question we need to answer before considering this tool is, do we see the Application Platform being deployed through AWS in the long term, and will the features of Codepipeline really outweigh using the `aws-cli` from a 3rd party CI tool. I've never had issues with this approach in the past. 

**Paid Solution**

Travis Enterprise would likely work for us out of the box. But no more so than an open source self-hosted solution, and no pricing indication is even given for Travis Enterprise without contacting the sales department. I don't think we need to consider this any further.

**Comment by Sam-Jeston** [comment]
As our Buildkite solution is now functional, @rhyslbw and I have agreed it is sensible to keep this as our solution for now. If requirements or complexity change in the future, this issue will be re-opened.
