### ISSUE TITLE
Docker images and stack definition

### ISSUE THREAD

**Issue by Sam-Jeston** [input-output-hk/smart-contract-backend#25]
We need to define the Docker images for this project.

We should also define a `docker-compose.yml` that spins up the dev stack. The boundaries between services need to be considered, including:

- API
- contract proxy
- Docker Execution Engine
  - Ensure the docker sock of the host machine can be mounted into the container
  - Networking should no longer use localhost. Instead, it will use the docker network to communicate with the other running containers
- event store
- triggers service

**Comment by rhyslbw** [comment]
Let's reflect the service definition in the structure under `/src`. Right now I see the services as:

- server: The core of the backend
  - API
  - Contract Proxy server
  - Event Store client
  - Triggers service
- docker execution engine

**Comment by Sam-Jeston** [comment]
PR #39
