### ISSUE TITLE
Rework 'Contract Bundles' to be a contract repository

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/smart-contract-backend#35]
https://github.com/input-output-hk/smart-contract-backend/tree/develop/src/server/infrastructure/bundle_fetcher

The controller should be interfacing with a repository. A bundle is just part of what defines a smart contract

**Comment by Sam-Jeston** [comment]
This should be implemented here: src/server/smart_contract_repository

**Comment by rhyslbw** [comment]
#57
