### ISSUE TITLE
Plutus contact accessibility for development

### ISSUE THREAD

**Issue by Sam-Jeston** [input-output-hk/smart-contract-backend#41]
As there is a high complexity in creating statically linked Plutus binaries, instead the initial development experience will facilitate the creation of Docker images from Plutus contracts.

@j-mueller is working on providing a Docker image for a Plutus contract.

To facilitate and test this in the Application Platform, we should:
1. Write a static bundle that represents this contract. This will include a reference to the contract image and the graphQL schema
2. Refactor our services to handle image references, rather than passing around the base64 encoded executable.
3. Create a development service in our docker-compose file that serves this bundle
5. Do an end to end test across the services to ensure things are configured as we expect (API -> contract proxy -> docker execution)

Jann's Plutus PR that contains this work is here: https://github.com/input-output-hk/plutus/pull/730

**Comment by rhyslbw** [comment]
👍

**Comment by rhyslbw** [comment]
> Create a development service in our docker-compose file serves this bundle

Let's treat the service as a first-class component _Bundle Server_  `src/bundle_server`, which we can include in the dev stack, but it should also be a useful tool for production deployments

**Comment by Sam-Jeston** [comment]
#46
