### ISSUE TITLE
Initial security analysis of chromium

### ISSUE THREAD

**Issue by Sam-Jeston** [input-output-hk/smart-contract-backend#66]
We need to understand, test and document the security characteristics of running arbitrary JS in a chromium instance. This should analyse the following:

- Isolation between contract pages
- Isolation between browser and host system
- Resource consumption vulnerabilities
- Malicious HTTP requests
- Load characteristics

This is just an initial piece of work that can be taken to experts and auditors for further analysis

**Comment by rhyslbw** [comment]
Done in #67
